# Generated by Django 4.0 on 2022-03-02 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'ordering': ['-end_Date']},
        ),
        migrations.AlterField(
            model_name='events',
            name='end_Date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='start_Date',
            field=models.DateTimeField(),
        ),
    ]
